### ISSUE TITLE
How to add multi-line support? 

### ISSUE THREAD

**Issue by falnatsheh** [fullc0de/HKKTagWriteView#5]
Hi, 

Any hint on how to add multi-line support to this? I'm planning to fork it and spend time looking into it just want to see if you have helpful tips to start with. 

Thanks!

**Comment by fullc0de** [comment]
Hi, @falnatsheh 
I'm sorry for late reply. I couldn't consider your question shortly because of my daily works. This view supports single line tag only. For a multiple lines feature, you could start from a delegate method `textView(textView: UITextView!, shouldChangeTextInRange range: NSRange, replacementText text: String!) -> Bool` and `isFinishLetter`. In methods, newline character is used to detect the end of tag. I think the point is good place to start to add the feature you want.

**Comment by falnatsheh** [comment]
Thanks a lot man! will start from there.
